{{ config(materialized='table') }}
WITH violations AS(
SELECT * FROM `cis9440gp.RawDataset.RestaurantInspection`),
violation_facts_table AS(
    SELECT DISTINCT camis AS unique_violation_id, grade_dim_id, violation_dim_id, location_dim_id, business_dim_id, date_dim_id
    FROM violations
    LEFT JOIN `cis9440gp.dbt_qlin.date_dimension` ON
        `cis9440gp.dbt_qlin.date_dimension`.date=DATE(violations.inspection_date)
    LEFT JOIN `cis9440gp.dbt_lsousa.grade_dim`
            ON CASE 
                WHEN violations.grade = 'A' THEN 'A'
                WHEN violations.grade = 'B' THEN 'B'
                WHEN violations.grade = 'C' THEN 'C'
                WHEN violations.grade IN ('Z', 'P') THEN 'Grade Pending'
                WHEN violations.grade = 'N' THEN 'Not Yet Graded'
                ELSE 'N/A'
            END = `cis9440gp.dbt_lsousa.grade_dim`.grade
    LEFT JOIN `cis9440gp.dbt_lsousa.violation_dim`
            ON CASE
                WHEN violations.violation_code = '09E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 1 THEN '09E'
                WHEN violations.violation_code = '09C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 2 THEN '09C'
                WHEN violations.violation_code = '28-04' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 3 THEN '28-04'
                WHEN violations.violation_code = '15-27' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 4 THEN '15-27'
                WHEN violations.violation_code = '10G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 5 THEN '10G'
                WHEN violations.violation_code = '02B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 6 THEN '02B'
                WHEN violations.violation_code = '04A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 7 THEN '04A'
                WHEN violations.violation_code = '10J' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 8 THEN '10J'
                WHEN violations.violation_code = '10C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 9 THEN '10C'
                WHEN violations.violation_code = '04L' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 10 THEN '04L'
                WHEN violations.violation_code = '04M' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 11 THEN '04M'
                WHEN violations.violation_code = '04A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 12 THEN '04A'
                WHEN violations.violation_code = '02B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 13 THEN '02B'
                WHEN violations.violation_code = '10F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 14 THEN '10F'
                WHEN violations.violation_code = '08A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 15 THEN '08A'
                WHEN violations.violation_code = '09B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 16 THEN '09B'
                WHEN violations.violation_code = '09C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 17 THEN '09C'
                WHEN violations.violation_code = '02G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 18 THEN '02G'
                WHEN violations.violation_code = '05H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 19 THEN '05H'
                WHEN violations.violation_code = '06E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 20 THEN '06E'
                WHEN violations.violation_code = '04K' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 21 THEN '04K'
                WHEN violations.violation_code = '06D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 22 THEN '06D'
                WHEN violations.violation_code = '04H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 23 THEN '04H'
                WHEN violations.violation_code = '10E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 24 THEN '10E'
                WHEN violations.violation_code = '06C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 25 THEN '06C'
                WHEN violations.violation_code = '22A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 26 THEN '22A'
                WHEN violations.violation_code = '04L' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 27 THEN '04L'
                WHEN violations.violation_code = '28-05' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 28 THEN '28-05'
                WHEN violations.violation_code = '10H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 29 THEN '10H'
                WHEN violations.violation_code = '06A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 30 THEN '06A'
                WHEN violations.violation_code = '04N' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 31 THEN '04N'
                WHEN violations.violation_code = '10D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 32 THEN '10D'
                WHEN violations.violation_code = '20D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 33 THEN '20D'
                WHEN violations.violation_code = '02H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 34 THEN '02H'
                WHEN violations.violation_code = '04N' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 35 THEN '04N'
                WHEN violations.violation_code = '10F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 36 THEN '10F'
                WHEN violations.violation_code = '06A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 37 THEN '06A'
                WHEN violations.violation_code = '04K' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 38 THEN '04K'
                WHEN violations.violation_code = '04E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 39 THEN '04E'
                WHEN violations.violation_code = '04N' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 40 THEN '04N'
                WHEN violations.violation_code = '02C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 41 THEN '02C'
                WHEN violations.violation_code = '06C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 42 THEN '06C'
                WHEN violations.violation_code = '06C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 43 THEN '06C'
                WHEN violations.violation_code = '05D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 44 THEN '05D'
                WHEN violations.violation_code = '06C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 45 THEN '06C'
                WHEN violations.violation_code = '08A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 46 THEN '08A'
                WHEN violations.violation_code = '10E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 47 THEN '10E'
                WHEN violations.violation_code = '10B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 48 THEN '10B'
                WHEN violations.violation_code = '02H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 49 THEN '02H'
                WHEN violations.violation_code = '10B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 50 THEN '10B'
                WHEN violations.violation_code = '10H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 51 THEN '10H'
                WHEN violations.violation_code = '02G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 52 THEN '02G'
                WHEN violations.violation_code = '05H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 53 THEN '05H'
                WHEN violations.violation_code = '10G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 54 THEN '10G'
                WHEN violations.violation_code = '10I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 55 THEN '10I'
                WHEN violations.violation_code = '28-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 56 THEN '28-06'
                WHEN violations.violation_code = '22F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 57 THEN '22F'
                WHEN violations.violation_code = '19-07' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 58 THEN '19-07'
                WHEN violations.violation_code = '20F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 59 THEN '20F'
                WHEN violations.violation_code = '04J' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 60 THEN '04J'
                WHEN violations.violation_code = '05D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 61 THEN '05D'
                WHEN violations.violation_code = '06B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 62 THEN '06B'
                WHEN violations.violation_code = '02H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 63 THEN '02H'
                WHEN violations.violation_code = '06F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 64 THEN '06F'
                WHEN violations.violation_code = '06B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 65 THEN '06B'
                WHEN violations.violation_code = '10A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 66 THEN '10A'
                WHEN violations.violation_code = '04C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 67 THEN '04C'
                WHEN violations.violation_code = '20-04' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 68 THEN '20-04'
                WHEN violations.violation_code = '09C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 69 THEN '09C'
                WHEN violations.violation_code = '19-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 70 THEN '19-06'
                WHEN violations.violation_code = '06A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 71 THEN '06A'
                WHEN violations.violation_code = '22C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 72 THEN '22C'
                WHEN violations.violation_code = '20-08' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 73 THEN '20-08'
                WHEN violations.violation_code = '08C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 74 THEN '08C'
                WHEN violations.violation_code = '04M' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 75 THEN '04M'
                WHEN violations.violation_code = '08C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 76 THEN '08C'
                WHEN violations.violation_code = '03I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 77 THEN '03I'
                WHEN violations.violation_code = '05A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 78 THEN '05A'
                WHEN violations.violation_code = '05D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 79 THEN '05D'
                WHEN violations.violation_code = '08C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 80 THEN '08C'
                WHEN violations.violation_code = '05A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 81 THEN '05A'
                WHEN violations.violation_code = '16-03' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 82 THEN '16-03'
                WHEN violations.violation_code = '16-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 83 THEN '16-06'
                WHEN violations.violation_code = '04J' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 84 THEN '04J'
                WHEN violations.violation_code = '08B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 85 THEN '08B'
                WHEN violations.violation_code = '06A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 86 THEN '06A'
                WHEN violations.violation_code = '04O' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 87 THEN '04O'
                WHEN violations.violation_code = '05F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 88 THEN '05F'
                WHEN violations.violation_code = '20-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 89 THEN '20-06'
                WHEN violations.violation_code = '20-04' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 90 THEN '20-04'
                WHEN violations.violation_code = '20-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 91 THEN '20-01'
                WHEN violations.violation_code = '04F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 92 THEN '04F'
                WHEN violations.violation_code = '03A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 93 THEN '03A'
                WHEN violations.violation_code = '03C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 94 THEN '03C'
                WHEN violations.violation_code = '06G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 95 THEN '06G'
                WHEN violations.violation_code = '09A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 96 THEN '09A'
                WHEN violations.violation_code = '15F6' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 97 THEN '15F6'
                WHEN violations.violation_code = '10C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 98 THEN '10C'
                WHEN violations.violation_code = '1500' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 99 THEN '1500'
                WHEN violations.violation_code = '04F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 100 THEN '04F'
                WHEN violations.violation_code = '10D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 101 THEN '10D'
                WHEN violations.violation_code = '03E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 102 THEN '03E'
                WHEN violations.violation_code = '18-11' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 103 THEN '18-11'
                WHEN violations.violation_code = '03A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 104 THEN '03A'
                WHEN violations.violation_code = '06F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 105 THEN '06F'
                WHEN violations.violation_code = '15-42' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 106 THEN '15-42'
                WHEN violations.violation_code = '15-21' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 107 THEN '15-21'
                WHEN violations.violation_code = '19-10' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 108 THEN '19-10'
                WHEN violations.violation_code = '20-05' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 109 THEN '20-05'
                WHEN violations.violation_code = '04E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 110 THEN '04E'
                WHEN violations.violation_code = '28-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 111 THEN '28-01'
                WHEN violations.violation_code = '02A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 112 THEN '02A'
                WHEN violations.violation_code = '15F7' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 113 THEN '15F7'
                WHEN violations.violation_code = '10H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 114 THEN '10H'
                WHEN violations.violation_code = '09B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 115 THEN '09B'
                WHEN violations.violation_code = '20A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 116 THEN '20A'
                WHEN violations.violation_code = '09A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 117 THEN '09A'
                WHEN violations.violation_code = '28-03' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 118 THEN '28-03'
                WHEN violations.violation_code = '16-02' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 119 THEN '16-02'
                WHEN violations.violation_code = '28-05' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 120 THEN '28-05'
                WHEN violations.violation_code = '04D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 121 THEN '04D'
                WHEN violations.violation_code = '28-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 122 THEN '28-06'
                WHEN violations.violation_code = '04C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 123 THEN '04C'
                WHEN violations.violation_code = '04F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 124 THEN '04F'
                WHEN violations.violation_code = '02D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 125 THEN '02D'
                WHEN violations.violation_code = '16-04' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 126 THEN '16-04'
                WHEN violations.violation_code = '05H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 127 THEN '05H'
                WHEN violations.violation_code = '02C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 128 THEN '02C'
                WHEN violations.violation_code = '02A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 129 THEN '02A'
                WHEN violations.violation_code = '05C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 130 THEN '05C'
                WHEN violations.violation_code = '03A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 131 THEN '03A'
                WHEN violations.violation_code = '03E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 132 THEN '03E'
                WHEN violations.violation_code = '05E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 133 THEN '05E'
                WHEN violations.violation_code = '19-05' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 134 THEN '19-05'
                WHEN violations.violation_code = '02F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 135 THEN '02F'
                WHEN violations.violation_code = '09A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 136 THEN '09A'
                WHEN violations.violation_code = '05F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 137 THEN '05F'
                WHEN violations.violation_code = '02I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 138 THEN '02I'
                WHEN violations.violation_code = '04O' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 139 THEN '04O'
                WHEN violations.violation_code = '04P' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 140 THEN '04P'
                WHEN violations.violation_code = '03B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 141 THEN '03B'
                WHEN violations.violation_code = '02C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 142 THEN '02C'
                WHEN violations.violation_code = '18-14' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 143 THEN '18-14'
                WHEN violations.violation_code = '10A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 144 THEN '10A'
                WHEN violations.violation_code = '02A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 145 THEN '02A'
                WHEN violations.violation_code = '15-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 146 THEN '15-01'
                WHEN violations.violation_code = '15-22' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 147 THEN '15-22'
                WHEN violations.violation_code = '15-32' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 148 THEN '15-32'
                WHEN violations.violation_code = '22G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 149 THEN '22G'
                WHEN violations.violation_code = '09D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 150 THEN '09D'
                WHEN violations.violation_code = '16E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 151 THEN '16E'
                WHEN violations.violation_code = '22E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 152 THEN '22E'
                WHEN violations.violation_code = '15-37' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 153 THEN '15-37'
                WHEN violations.violation_code = '08B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 154 THEN '08B'
                WHEN violations.violation_code = '03B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 155 THEN '03B'
                WHEN violations.violation_code = '05B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 156 THEN '05B'
                WHEN violations.violation_code = '20E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 157 THEN '20E'
                WHEN violations.violation_code = '05B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 158 THEN '05B'
                WHEN violations.violation_code = '04I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 159 THEN '04I'
                WHEN violations.violation_code = '19-11' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 160 THEN '19-11'
                WHEN violations.violation_code = '16-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 161 THEN '16-01'
                WHEN violations.violation_code = '18-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 162 THEN '18-01'
                WHEN violations.violation_code = '19-10' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 163 THEN '19-10'
                WHEN violations.violation_code = '18G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 164 THEN '18G'
                WHEN violations.violation_code = '19-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 165 THEN '19-01'
                WHEN violations.violation_code = '16B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 166 THEN '16B'
                WHEN violations.violation_code = '15F1' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 167 THEN '15F1'
                WHEN violations.violation_code = '07A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 168 THEN '07A'
                WHEN violations.violation_code = '02F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 169 THEN '02F'
                WHEN violations.violation_code = '18F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 170 THEN '18F'
                WHEN violations.violation_code = '05C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 171 THEN '05C'
                WHEN violations.violation_code = '16D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 172 THEN '16D'
                WHEN violations.violation_code = '16C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 173 THEN '16C'
                WHEN violations.violation_code = '05B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 174 THEN '05B'
                WHEN violations.violation_code = '18C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 175 THEN '18C'
                WHEN violations.violation_code = '16-10' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 176 THEN '16-10'
                WHEN violations.violation_code = '04D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 177 THEN '04D'
                WHEN violations.violation_code = '18-08' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 178 THEN '18-08'
                WHEN violations.violation_code = '03E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 179 THEN '03E'
                WHEN violations.violation_code = '06I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 180 THEN '06I'
                WHEN violations.violation_code = '06H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 181 THEN '06H'
                WHEN violations.violation_code = '16-09' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 182 THEN '16-09'
                WHEN violations.violation_code = '04D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 183 THEN '04D'
                WHEN violations.violation_code = '03F' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 184 THEN '03F'
                WHEN violations.violation_code = '02I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 185 THEN '02I'
                WHEN violations.violation_code = '05C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 186 THEN '05C'
                WHEN violations.violation_code = '20-06' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 187 THEN '20-06'
                WHEN violations.violation_code = '16-08' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 188 THEN '16-08'
                WHEN violations.violation_code = '05E' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 189 THEN '05E'
                WHEN violations.violation_code = '03D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 190 THEN '03D'
                WHEN violations.violation_code = '18-13' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 191 THEN '18-13'
                WHEN violations.violation_code = '16J' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 192 THEN '16J'
                WHEN violations.violation_code = '16L' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 193 THEN '16L'
                WHEN violations.violation_code = '05C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 194 THEN '05C'
                WHEN violations.violation_code = '03C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 195 THEN '03C'
                WHEN violations.violation_code = '18-12' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 196 THEN '18-12'
                WHEN violations.violation_code = '04I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 197 THEN '04I'
                WHEN violations.violation_code = '06I' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 198 THEN '06I'
                WHEN violations.violation_code = '06H' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 199 THEN '06H'
                WHEN violations.violation_code = '02D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 200 THEN '02D'
                WHEN violations.violation_code = '19-04' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 201 THEN '19-04'
                WHEN violations.violation_code = '03G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 202 THEN '03G'
                WHEN violations.violation_code = '16K' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 203 THEN '16K'
                WHEN violations.violation_code = '19-08' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 204 THEN '19-08'
                WHEN violations.violation_code = '19-01' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 205 THEN '19-01'
                WHEN violations.violation_code = '19-03' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 206 THEN '19-03'
                WHEN violations.violation_code = '04B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 207 THEN '04B'
                WHEN violations.violation_code = '04B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 208 THEN '04B'
                WHEN violations.violation_code = '03G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 209 THEN '03G'
                WHEN violations.violation_code = '18B' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 210 THEN '18B'
                WHEN violations.violation_code = '16A' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 211 THEN '16A'
                WHEN violations.violation_code = '15-17' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 212 THEN '15-17'
                WHEN violations.violation_code = '15-39' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 213 THEN '15-39'
                WHEN violations.violation_code = '15A1' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 214 THEN '15A1'
                WHEN violations.violation_code = '28-07' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 215 THEN '28-07'
                WHEN violations.violation_code = '20-07' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 216 THEN '20-07'
                WHEN violations.violation_code = '15F2' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 217 THEN '15F2'
                WHEN violations.violation_code = '03D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 218 THEN '03D'
                WHEN violations.violation_code = '18D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 219 THEN '18D'
                WHEN violations.violation_code = '03D' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 220 THEN '03D'
                WHEN violations.violation_code = '15-33' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 221 THEN '15-33'
                WHEN violations.violation_code = '15000' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 222 THEN '15000'
                WHEN violations.violation_code = '15-36' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 223 THEN '15-36'
                WHEN violations.violation_code = '20C' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 224 THEN '20C'
                WHEN violations.violation_code = '10G' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 225 THEN '10G'
                WHEN violations.violation_code = '18-02' AND `cis9440gp.dbt_lsousa.violation_dim`.violation_dim_id = 226 THEN '18-02'
                ELSE 'N/A'
                END = `cis9440gp.dbt_lsousa.violation_dim`.violation_code
    LEFT JOIN `cis9440gp.dbt_qlin.location_dimension` 
            ON CASE
                WHEN violations.community_board ='164' THEN '100'
                WHEN violations.community_board like '22%' THEN '200'
                WHEN violations.community_board like '355' THEN '300'
                WHEN violations.community_board like '48%' THEN '400'
                WHEN violations.community_board='595' THEN '500'
                WHEN violations.boro ='Manhattan' AND violations.community_board IS NULL THEN '100'
                WHEN violations.boro ='Bronx' AND violations.community_board IS NULL THEN '200'
                WHEN violations.boro ='Brooklyn' AND violations.community_board IS NULL THEN '300'
                WHEN violations.boro ='Queens' AND violations.community_board IS NULL THEN '400'
                WHEN violations.boro ='Staten Island' AND violations.community_board IS NULL THEN '500'
                ELSE violations.community_board 
                END = `cis9440gp.dbt_qlin.location_dimension`.community_board AND
            COALESCE(violations.zipcode,'99999') = `cis9440gp.dbt_qlin.location_dimension`.zipcode AND
            COALESCE(violations.street,'Unspecified') = `cis9440gp.dbt_qlin.location_dimension`.street_address
            AND UPPER(violations.boro) = `cis9440gp.dbt_qlin.location_dimension`.city_borough
            AND violations.street=`cis9440gp.dbt_qlin.location_dimension`.street_address
            AND violations.zipcode = `cis9440gp.dbt_qlin.location_dimension`.zipcode 
    LEFT JOIN `cis9440gp.dbt_lsousa.business_dim`
    ON `cis9440gp.dbt_lsousa.business_dim`.business_name = violations.dba
        AND `cis9440gp.dbt_lsousa.business_dim`.cuisine_description = violations.cuisine_description 
        AND `cis9440gp.dbt_lsousa.business_dim`.address = CONCAT(violations.building,' ', violations.street))
            SELECT * FROM violation_facts_table WHERE location_dim_id = 241